language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - composer self-update

install:
  - composer install

script: vendor/bin/phpunit
